import type { Card } from '@/features/gameConfig/cardTypes';

const REWARD_CARD_POOL: Card[] = [
  // Fire
  {
    id: 'flame-burst',
    name: 'Flame Burst',
    cost: 2,
    trait: 'fire',
    description: 'Deal 14 damage.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Inferno Burst',
    upgradeDescription: 'Deal 20 damage.',
    baseDamage: 14,
    upgradedDamage: 20,
  },
  {
    id: 'eruption',
    name: 'Eruption',
    cost: 3,
    trait: 'fire',
    description: 'Deal 22 damage to all.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Cataclysm',
    upgradeDescription: 'Deal 30 damage to all.',
    baseDamage: 22,
    upgradedDamage: 30,
    isAoe: true,
    isRare: true,
  },
  {
    id: 'kindle',
    name: 'Kindle',
    cost: 0,
    trait: 'fire',
    description: 'Deal 3 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Kindle+',
    upgradeDescription: 'Deal 5 damage. +1 Fire charge.',
    baseDamage: 3,
    upgradedDamage: 5,
  },
  {
    id: 'immolate',
    name: 'Immolate',
    cost: 2,
    trait: 'fire',
    description: 'Deal 6 damage. Burn 10.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Immolate+',
    upgradeDescription: 'Deal 10 damage. Burn 15.',
    baseDamage: 6,
    upgradedDamage: 10,
    baseBurn: 10,
    upgradedBurn: 15,
  },
  {
    id: 'sear',
    name: 'Sear',
    cost: 0,
    trait: 'fire',
    description: 'Burn 4.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Sear+',
    upgradeDescription: 'Burn 7.',
    baseBurn: 4,
    upgradedBurn: 7,
  },
  // Guard
  {
    id: 'counter-guard',
    name: 'Counter Guard',
    cost: 2,
    trait: 'guard',
    description: 'Gain 8 Block. If hit, deal 6 back.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Iron Counter',
    upgradeDescription: 'Gain 12 Block. If hit, deal 10 back.',
    baseDamage: 6,
    baseBlock: 8,
    upgradedDamage: 10,
    upgradedBlock: 12,
  },
  {
    id: 'bulwark',
    name: 'Bulwark',
    cost: 3,
    trait: 'guard',
    description: 'Gain 18 Block. +2 Thorns.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Great Bulwark',
    upgradeDescription: 'Gain 25 Block. +4 Thorns.',
    baseDamage: 2,
    baseBlock: 18,
    upgradedDamage: 4,
    upgradedBlock: 25,
    isRare: true,
  },
  {
    id: 'brace',
    name: 'Brace',
    cost: 0,
    trait: 'guard',
    description: 'Gain 3 Block.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Brace+',
    upgradeDescription: 'Gain 5 Block.',
    baseBlock: 3,
    upgradedBlock: 5,
  },
  // Shadow
  {
    id: 'poison-edge',
    name: 'Poison Edge',
    cost: 1,
    trait: 'shadow',
    description: 'Deal 4 damage. Weaken 2 turns.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Venom Edge',
    upgradeDescription: 'Deal 7 damage. Weaken 3 turns.',
    baseDamage: 4,
    upgradedDamage: 7,
  },
  {
    id: 'backstab',
    name: 'Backstab',
    cost: 2,
    trait: 'shadow',
    description: 'Deal 10 damage. +5 if Vulnerable.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Assassinate',
    upgradeDescription: 'Deal 14 damage. +8 if Vuln.',
    baseDamage: 10,
    upgradedDamage: 14,
  },
  {
    id: 'death-sentence',
    name: 'Death Sentence',
    cost: 3,
    trait: 'shadow',
    description: 'Deal 8 dmg. Execute below 25%.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Execution',
    upgradeDescription: 'Deal 12 dmg. Execute below 30%.',
    baseDamage: 8,
    upgradedDamage: 12,
    isRare: true,
  },
  // Storm
  {
    id: 'tempest-flow',
    name: 'Tempest Flow',
    cost: 2,
    trait: 'storm',
    description: '+1 energy next turn.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Tempest Surge',
    upgradeDescription: '+2 energy next turn.',
    baseDamage: 0,
    upgradedDamage: 0,
  },
  {
    id: 'thunderstrike',
    name: 'Thunderstrike',
    cost: 3,
    trait: 'storm',
    description: 'Deal 16 damage. +1 energy.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Thunderstrike+',
    upgradeDescription: 'Deal 22 damage. +2 energy.',
    baseDamage: 16,
    upgradedDamage: 22,
    isRare: true,
  },
  // Nature
  {
    id: 'mend',
    name: 'Mend',
    cost: 1,
    trait: 'nature',
    description: 'Heal 6 HP.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Mend+',
    upgradeDescription: 'Heal 10 HP. +1 Regen.',
    baseHeal: 6,
    upgradedHeal: 10,
  },
  {
    id: 'bramble-wall',
    name: 'Bramble Wall',
    cost: 1,
    trait: 'nature',
    description: 'Gain 5 Block + 2 Thorns.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Bramble Wall+',
    upgradeDescription: 'Gain 8 Block + 3 Thorns.',
    baseDamage: 2,
    baseBlock: 5,
    upgradedDamage: 3,
    upgradedBlock: 8,
  },
  {
    id: 'natures-wrath',
    name: "Nature's Wrath",
    cost: 3,
    trait: 'nature',
    description: 'Deal 12 dmg. Heal equal.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: "Nature's Fury",
    upgradeDescription: 'Deal 18 dmg. Heal equal.',
    baseDamage: 12,
    upgradedDamage: 18,
    isRare: true,
  },
];

export { REWARD_CARD_POOL };
