import type { Card } from '@/features/gameConfig/cardTypes';

const WARRIOR_STARTER: Card[] = [
  // ── Rage (3 starters) ──────────────────────────────────────────
  {
    id: 'w-strike',
    name: 'Strike',
    cost: 1,
    trait: 'rage',
    description: 'Deal 8 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Strike+',
    upgradeDescription: 'Deal 11 damage.',
    baseDamage: 8,
    upgradedDamage: 11,
    starterRole: 'warrior',
  },
  {
    id: 'w-quick-slash',
    name: 'Quick Slash',
    cost: 0,
    trait: 'rage',
    description: 'Deal 3 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Quick Slash+',
    upgradeDescription: 'Deal 5 damage.',
    baseDamage: 3,
    upgradedDamage: 5,
    starterRole: 'warrior',
  },
  {
    id: 'w-heavy-blow',
    name: 'Heavy Blow',
    cost: 2,
    trait: 'rage',
    description: 'Deal 14 damage.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Crushing Blow',
    upgradeDescription: 'Deal 19 damage.',
    baseDamage: 14,
    upgradedDamage: 19,
    starterRole: 'warrior',
  },
  // ── Iron (3 starters) ──────────────────────────────────────────
  {
    id: 'w-guard',
    name: 'Guard',
    cost: 1,
    trait: 'iron',
    description: 'Gain 7 Block.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Guard+',
    upgradeDescription: 'Gain 10 Block.',
    baseBlock: 7,
    upgradedBlock: 10,
    starterRole: 'warrior',
    vfxEffectId: 'ShieldSelf',
    vfxTarget: 'self',
  },
  {
    id: 'w-brace',
    name: 'Brace',
    cost: 0,
    trait: 'iron',
    description: 'Gain 3 Block.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Brace+',
    upgradeDescription: 'Gain 5 Block.',
    baseBlock: 3,
    upgradedBlock: 5,
    starterRole: 'warrior',
    vfxEffectId: 'ShieldSelf',
    vfxTarget: 'self',
  },
  {
    id: 'w-fortify',
    name: 'Fortify',
    cost: 2,
    trait: 'iron',
    description: 'Gain 12 Block.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Fortify+',
    upgradeDescription: 'Gain 16 Block.',
    baseBlock: 12,
    upgradedBlock: 16,
    starterRole: 'warrior',
    vfxEffectId: 'ShieldSelf',
    vfxTarget: 'self',
  },
  // ── Blood (3 starters) ─────────────────────────────────────────
  {
    id: 'w-drain-strike',
    name: 'Drain Strike',
    cost: 1,
    trait: 'blood',
    description: 'Deal 5 damage. Heal 3.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Drain Strike+',
    upgradeDescription: 'Deal 7 damage. Heal 5.',
    baseDamage: 5,
    upgradedDamage: 7,
    baseHeal: 3,
    upgradedHeal: 5,
    starterRole: 'warrior',
    vfxSequenceId: 'Seq_GreenTest',
    vfxTarget: 'self_to_target',
  },
  {
    id: 'w-blood-pact',
    name: 'Blood Pact',
    cost: 0,
    trait: 'blood',
    description: 'Heal 2.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Blood Pact+',
    upgradeDescription: 'Heal 4.',
    baseHeal: 2,
    upgradedHeal: 4,
    starterRole: 'warrior',
    vfxSequenceId: 'Seq_GreenTest',
    vfxTarget: 'self',
  },
  {
    id: 'w-siphon',
    name: 'Siphon',
    cost: 2,
    trait: 'blood',
    description: 'Deal 8 damage. Heal 6.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Siphon+',
    upgradeDescription: 'Deal 11 damage. Heal 8.',
    baseDamage: 8,
    upgradedDamage: 11,
    baseHeal: 6,
    upgradedHeal: 8,
    starterRole: 'warrior',
    vfxSequenceId: 'Seq_GreenTest',
    vfxTarget: 'self_to_target',
  },
  // ── Thunder (3 starters) ───────────────────────────────────────
  {
    id: 'w-shock',
    name: 'Shock',
    cost: 1,
    trait: 'thunder',
    description: 'Deal 6 damage. Weak 1.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Shock+',
    upgradeDescription: 'Deal 9 damage. Weak 1.',
    baseDamage: 6,
    upgradedDamage: 9,
    starterRole: 'warrior',
    vfxSequenceId: 'Seq_IceShard',
    vfxTarget: 'self_to_target',
  },
  {
    id: 'w-spark',
    name: 'Spark',
    cost: 0,
    trait: 'thunder',
    description: 'Deal 2 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Spark+',
    upgradeDescription: 'Deal 4 damage.',
    baseDamage: 2,
    upgradedDamage: 4,
    starterRole: 'warrior',
    vfxSequenceId: 'Seq_IceShard',
    vfxTarget: 'self_to_target',
  },
  {
    id: 'w-lightning-strike',
    name: 'Lightning Strike',
    cost: 2,
    trait: 'thunder',
    description: 'Deal 12 damage. Vuln 1.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Lightning Strike+',
    upgradeDescription: 'Deal 16 damage. Vuln 1.',
    baseDamage: 12,
    upgradedDamage: 16,
    starterRole: 'warrior',
  },
];

export { WARRIOR_STARTER };
