import type { Card } from '@/features/gameConfig/cardTypes';

const RANGER_STARTER: Card[] = [
  // Shadow (5)
  {
    id: 'r-shadow-mark',
    name: 'Shadow Mark',
    cost: 1,
    trait: 'shadow',
    description: 'Apply Vulnerable 2 turns.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Deep Mark',
    upgradeDescription: 'Vuln 3 turns. Deal 4 damage.',
    baseDamage: 0,
    upgradedDamage: 4,
    starterRole: 'ranger',
  },
  {
    id: 'r-ambush',
    name: 'Ambush',
    cost: 2,
    trait: 'shadow',
    description: 'Deal 10 damage. +5 if Vuln.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Ambush+',
    upgradeDescription: 'Deal 13 damage. +8 if Vuln.',
    baseDamage: 10,
    upgradedDamage: 13,
    starterRole: 'ranger',
  },
  {
    id: 'r-poison-arrow',
    name: 'Poison Arrow',
    cost: 1,
    trait: 'shadow',
    description: 'Deal 4 damage. Burn 4.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Venom Arrow',
    upgradeDescription: 'Deal 7 damage. Burn 6.',
    baseDamage: 4,
    upgradedDamage: 7,
    baseBurn: 4,
    upgradedBurn: 6,
    starterRole: 'ranger',
  },
  {
    id: 'r-nick',
    name: 'Nick',
    cost: 0,
    trait: 'shadow',
    description: 'Deal 2 damage. Weaken 1.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Nick+',
    upgradeDescription: 'Deal 4 damage. Weaken 1. Vuln 1.',
    baseDamage: 2,
    upgradedDamage: 4,
    starterRole: 'ranger',
  },
  {
    id: 'r-smoke-bomb',
    name: 'Smoke Bomb',
    cost: 1,
    trait: 'shadow',
    description: 'Gain 5 Block. Weaken 1.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Smoke Bomb+',
    upgradeDescription: 'Gain 7 Block. Weaken 2.',
    baseBlock: 5,
    upgradedBlock: 7,
    starterRole: 'ranger',
  },
  // Nature (4)
  {
    id: 'r-vine-lash',
    name: 'Vine Lash',
    cost: 1,
    trait: 'nature',
    description: 'Deal 3 damage. Heal 5 HP.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Vine Lash+',
    upgradeDescription: 'Deal 6 damage. Heal 8 HP.',
    baseDamage: 3,
    upgradedDamage: 6,
    baseHeal: 5,
    upgradedHeal: 8,
    starterRole: 'ranger',
  },
  {
    id: 'r-regrowth',
    name: 'Regrowth',
    cost: 1,
    trait: 'nature',
    description: 'Heal 6 HP.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Regrowth+',
    upgradeDescription: 'Heal 10 HP. +1 Regen.',
    baseHeal: 6,
    upgradedHeal: 10,
    starterRole: 'ranger',
  },
  {
    id: 'r-thorn-burst',
    name: 'Thorn Burst',
    cost: 1,
    trait: 'nature',
    description: 'Deal 3 damage to all.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Thorn Burst+',
    upgradeDescription: 'Deal 6 damage to all.',
    baseDamage: 3,
    upgradedDamage: 6,
    isAoe: true,
    starterRole: 'ranger',
  },
  {
    id: 'r-sprout',
    name: 'Sprout',
    cost: 0,
    trait: 'nature',
    description: 'Heal 2 HP.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Sprout+',
    upgradeDescription: 'Heal 4 HP. +1 Regen.',
    baseHeal: 2,
    upgradedHeal: 4,
    starterRole: 'ranger',
  },
  // Fire (2)
  {
    id: 'r-flame-arrow',
    name: 'Flame Arrow',
    cost: 1,
    trait: 'fire',
    description: 'Deal 6 damage. Burn 3.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Flame Arrow+',
    upgradeDescription: 'Deal 8 damage. Burn 5.',
    baseDamage: 6,
    upgradedDamage: 8,
    baseBurn: 3,
    upgradedBurn: 5,
    starterRole: 'ranger',
  },
  {
    id: 'r-volley',
    name: 'Volley',
    cost: 2,
    trait: 'fire',
    description: 'Deal 8 damage to all.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Volley+',
    upgradeDescription: 'Deal 12 damage to all.',
    baseDamage: 8,
    upgradedDamage: 12,
    isAoe: true,
    starterRole: 'ranger',
  },
  // Guard (1)
  {
    id: 'r-dodge',
    name: 'Dodge',
    cost: 0,
    trait: 'guard',
    description: 'Gain 3 Block.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Dodge+',
    upgradeDescription: 'Gain 5 Block.',
    baseBlock: 3,
    upgradedBlock: 5,
    starterRole: 'ranger',
  },
  // Storm (1)
  {
    id: 'r-quick-shot',
    name: 'Quick Shot',
    cost: 0,
    trait: 'storm',
    description: 'Deal 2 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Quick Shot+',
    upgradeDescription: 'Deal 4 damage. +1 energy if chained.',
    baseDamage: 2,
    upgradedDamage: 4,
    starterRole: 'ranger',
  },
  // Neutral (2)
  {
    id: 'r-snipe',
    name: 'Snipe',
    cost: 3,
    trait: 'neutral',
    description: 'Deal 20 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Snipe+',
    upgradeDescription: 'Deal 26 damage.',
    baseDamage: 20,
    upgradedDamage: 26,
    starterRole: 'ranger',
  },
  {
    id: 'r-focus',
    name: 'Focus',
    cost: 1,
    trait: 'neutral',
    description: 'Transform into random card.',
    upgraded: false,
    upgradeThreshold: 99,
    upgradeName: 'Focus+',
    upgradeDescription: 'Transform. Costs 0.',
    starterRole: 'ranger',
  },
];

export { RANGER_STARTER };
