import type { Card } from '@/features/gameConfig/cardTypes';

const RANGER_STARTER: Card[] = [
  // ── Shadow (3 starters) ────────────────────────────────────────
  {
    id: 'r-shadow-mark',
    name: 'Shadow Mark',
    cost: 1,
    trait: 'shadow',
    description: 'Deal 4 damage. Vuln 2.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Deep Mark',
    upgradeDescription: 'Deal 6 damage. Vuln 3.',
    baseDamage: 4,
    upgradedDamage: 6,
    starterRole: 'ranger',
  },
  {
    id: 'r-nick',
    name: 'Nick',
    cost: 0,
    trait: 'shadow',
    description: 'Deal 2 damage. Weak 1.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Nick+',
    upgradeDescription: 'Deal 4 damage. Weak 1.',
    baseDamage: 2,
    upgradedDamage: 4,
    starterRole: 'ranger',
    vfxSequenceId: 'Seq_IceShard',
    vfxTarget: 'self_to_target',
  },
  {
    id: 'r-ambush',
    name: 'Ambush',
    cost: 2,
    trait: 'shadow',
    description: 'Deal 12 damage.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Ambush+',
    upgradeDescription: 'Deal 16 damage.',
    baseDamage: 12,
    upgradedDamage: 16,
    starterRole: 'ranger',
  },
  // ── Nature (3 starters) ────────────────────────────────────────
  {
    id: 'r-sprout',
    name: 'Sprout',
    cost: 0,
    trait: 'nature',
    description: 'Heal 3.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Sprout+',
    upgradeDescription: 'Heal 5.',
    baseHeal: 3,
    upgradedHeal: 5,
    starterRole: 'ranger',
    vfxSequenceId: 'Seq_GreenTest',
    vfxTarget: 'self',
  },
  {
    id: 'r-vine-lash',
    name: 'Vine Lash',
    cost: 1,
    trait: 'nature',
    description: 'Deal 4 damage. Heal 4.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Vine Lash+',
    upgradeDescription: 'Deal 6 damage. Heal 6.',
    baseDamage: 4,
    upgradedDamage: 6,
    baseHeal: 4,
    upgradedHeal: 6,
    starterRole: 'ranger',
    vfxSequenceId: 'Seq_GreenTest',
    vfxTarget: 'self_to_target',
  },
  {
    id: 'r-regrowth',
    name: 'Regrowth',
    cost: 2,
    trait: 'nature',
    description: 'Heal 8. +1 Regen.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Regrowth+',
    upgradeDescription: 'Heal 12. +2 Regen.',
    baseHeal: 8,
    upgradedHeal: 12,
    starterRole: 'ranger',
    vfxSequenceId: 'Seq_GreenTest',
    vfxTarget: 'self',
  },
  // ── Precision (3 starters) ─────────────────────────────────────
  {
    id: 'r-quick-shot',
    name: 'Quick Shot',
    cost: 0,
    trait: 'precision',
    description: 'Deal 3 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Quick Shot+',
    upgradeDescription: 'Deal 5 damage.',
    baseDamage: 3,
    upgradedDamage: 5,
    starterRole: 'ranger',
  },
  {
    id: 'r-aimed-shot',
    name: 'Aimed Shot',
    cost: 1,
    trait: 'precision',
    description: 'Deal 9 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Aimed Shot+',
    upgradeDescription: 'Deal 12 damage.',
    baseDamage: 9,
    upgradedDamage: 12,
    starterRole: 'ranger',
  },
  {
    id: 'r-snipe',
    name: 'Snipe',
    cost: 2,
    trait: 'precision',
    description: 'Deal 16 damage.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Snipe+',
    upgradeDescription: 'Deal 22 damage.',
    baseDamage: 16,
    upgradedDamage: 22,
    starterRole: 'ranger',
  },
  // ── Venom (3 starters) ─────────────────────────────────────────
  {
    id: 'r-poison-dart',
    name: 'Poison Dart',
    cost: 0,
    trait: 'venom',
    description: 'Burn 3.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Poison Dart+',
    upgradeDescription: 'Burn 5.',
    baseBurn: 3,
    upgradedBurn: 5,
    starterRole: 'ranger',
  },
  {
    id: 'r-toxic-strike',
    name: 'Toxic Strike',
    cost: 1,
    trait: 'venom',
    description: 'Deal 5 damage. Burn 4.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Toxic Strike+',
    upgradeDescription: 'Deal 7 damage. Burn 6.',
    baseDamage: 5,
    upgradedDamage: 7,
    baseBurn: 4,
    upgradedBurn: 6,
    starterRole: 'ranger',
  },
  {
    id: 'r-acid-splash',
    name: 'Acid Splash',
    cost: 2,
    trait: 'venom',
    description: 'Deal 6 damage to all. Burn 3.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Acid Splash+',
    upgradeDescription: 'Deal 9 damage to all. Burn 5.',
    baseDamage: 6,
    upgradedDamage: 9,
    baseBurn: 3,
    upgradedBurn: 5,
    isAoe: true,
    starterRole: 'ranger',
  },
];

export { RANGER_STARTER };
