import type { Card } from '@/features/gameConfig/cardTypes';

const WARRIOR_STARTER: Card[] = [
  // Guard (5)
  {
    id: 'w-guard-stance',
    name: 'Guard Stance',
    cost: 1,
    trait: 'guard',
    description: 'Gain 7 Block.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Guard Stance+',
    upgradeDescription: 'Gain 10 Block. Deal 2 damage.',
    baseBlock: 7,
    upgradedBlock: 10,
    upgradedDamage: 2,
    starterRole: 'warrior',
  },
  {
    id: 'w-fortify',
    name: 'Fortify',
    cost: 2,
    trait: 'guard',
    description: 'Gain 12 Block. Persists.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Fortify+',
    upgradeDescription: 'Gain 16 Block. Persists.',
    baseBlock: 12,
    upgradedBlock: 16,
    starterRole: 'warrior',
  },
  {
    id: 'w-shield-bash',
    name: 'Shield Bash',
    cost: 1,
    trait: 'guard',
    description: 'Gain 4 Block. Deal 4 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Shield Bash+',
    upgradeDescription: 'Gain 6 Block. Deal 6 damage.',
    baseDamage: 4,
    baseBlock: 4,
    upgradedDamage: 6,
    upgradedBlock: 6,
    starterRole: 'warrior',
  },
  {
    id: 'w-iron-wall',
    name: 'Iron Wall',
    cost: 2,
    trait: 'guard',
    description: 'Gain 10 Block. +2 Thorns.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Iron Wall+',
    upgradeDescription: 'Gain 14 Block. +3 Thorns.',
    baseBlock: 10,
    upgradedBlock: 14,
    starterRole: 'warrior',
  },
  {
    id: 'w-brace',
    name: 'Brace',
    cost: 0,
    trait: 'guard',
    description: 'Gain 3 Block.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Brace+',
    upgradeDescription: 'Gain 5 Block.',
    baseBlock: 3,
    upgradedBlock: 5,
    starterRole: 'warrior',
  },
  // Fire (3)
  {
    id: 'w-cleave',
    name: 'Cleave',
    cost: 1,
    trait: 'fire',
    description: 'Deal 6 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Cleave+',
    upgradeDescription: 'Deal 9 damage.',
    baseDamage: 6,
    upgradedDamage: 9,
    starterRole: 'warrior',
  },
  {
    id: 'w-reckless-swing',
    name: 'Reckless Swing',
    cost: 2,
    trait: 'fire',
    description: 'Deal 14 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Reckless Swing+',
    upgradeDescription: 'Deal 18 damage.',
    baseDamage: 14,
    upgradedDamage: 18,
    starterRole: 'warrior',
  },
  {
    id: 'w-war-cry',
    name: 'War Cry',
    cost: 2,
    trait: 'fire',
    description: 'Deal 8 damage to all.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'War Cry+',
    upgradeDescription: 'Deal 12 damage to all.',
    baseDamage: 8,
    upgradedDamage: 12,
    isAoe: true,
    starterRole: 'warrior',
  },
  // Nature (3)
  {
    id: 'w-battle-mend',
    name: 'Battle Mend',
    cost: 1,
    trait: 'nature',
    description: 'Heal 6 HP.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Battle Mend+',
    upgradeDescription: 'Heal 10 HP.',
    baseHeal: 6,
    upgradedHeal: 10,
    starterRole: 'warrior',
  },
  {
    id: 'w-second-wind',
    name: 'Second Wind',
    cost: 0,
    trait: 'nature',
    description: 'Heal 3 HP.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Second Wind+',
    upgradeDescription: 'Heal 5 HP. +1 Regen.',
    baseHeal: 3,
    upgradedHeal: 5,
    starterRole: 'warrior',
  },
  {
    id: 'w-vine-armor',
    name: 'Vine Armor',
    cost: 1,
    trait: 'nature',
    description: 'Gain 5 Block. Heal 3 HP.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Vine Armor+',
    upgradeDescription: 'Gain 7 Block. Heal 5 HP.',
    baseBlock: 5,
    baseHeal: 3,
    upgradedBlock: 7,
    upgradedHeal: 5,
    starterRole: 'warrior',
  },
  // Shadow (1)
  {
    id: 'w-provoke',
    name: 'Provoke',
    cost: 0,
    trait: 'shadow',
    description: 'Deal 2 damage. Weaken 1.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Provoke+',
    upgradeDescription: 'Deal 4 damage. Weaken 1.',
    baseDamage: 2,
    upgradedDamage: 4,
    starterRole: 'warrior',
  },
  // Storm (1)
  {
    id: 'w-battle-shout',
    name: 'Battle Shout',
    cost: 0,
    trait: 'storm',
    description: 'Deal 2 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Battle Shout+',
    upgradeDescription: 'Deal 4 damage. +1 energy if chained.',
    baseDamage: 2,
    upgradedDamage: 4,
    starterRole: 'warrior',
  },
  // Neutral (2)
  {
    id: 'w-haymaker',
    name: 'Haymaker',
    cost: 3,
    trait: 'neutral',
    description: 'Deal 18 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Haymaker+',
    upgradeDescription: 'Deal 24 damage.',
    baseDamage: 18,
    upgradedDamage: 24,
    starterRole: 'warrior',
  },
  {
    id: 'w-focus',
    name: 'Focus',
    cost: 1,
    trait: 'neutral',
    description: 'Transform into random card.',
    upgraded: false,
    upgradeThreshold: 99,
    upgradeName: 'Focus+',
    upgradeDescription: 'Transform. Costs 0.',
    starterRole: 'warrior',
  },
];

export { WARRIOR_STARTER };
