import type { Card } from '@/features/gameConfig/cardTypes';

const SAGE_STARTER: Card[] = [
  // ── Fire (3 starters) ──────────────────────────────────────────
  {
    id: 's-fireball',
    name: 'Fireball',
    cost: 1,
    trait: 'fire',
    description: 'Deal 7 damage. Burn 3.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Fireball+',
    upgradeDescription: 'Deal 10 damage. Burn 5.',
    baseDamage: 7,
    upgradedDamage: 10,
    baseBurn: 3,
    upgradedBurn: 5,
    starterRole: 'sage',
    vfxSequenceId: 'Seq_fireball',
    vfxTarget: 'self_to_target',
  },
  {
    id: 's-kindle',
    name: 'Kindle',
    cost: 0,
    trait: 'fire',
    description: 'Deal 3 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Kindle+',
    upgradeDescription: 'Deal 5 damage.',
    baseDamage: 3,
    upgradedDamage: 5,
    starterRole: 'sage',
    vfxSequenceId: 'Seq_fireball',
    vfxTarget: 'self_to_target',
  },
  {
    id: 's-flame-wave',
    name: 'Flame Wave',
    cost: 2,
    trait: 'fire',
    description: 'Deal 10 damage to all.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Flame Wave+',
    upgradeDescription: 'Deal 14 damage to all.',
    baseDamage: 10,
    upgradedDamage: 14,
    isAoe: true,
    starterRole: 'sage',
  },
  // ── Frost (3 starters) ─────────────────────────────────────────
  {
    id: 's-ice-shard',
    name: 'Ice Shard',
    cost: 1,
    trait: 'frost',
    description: 'Deal 6 damage. Weak 1.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Ice Shard+',
    upgradeDescription: 'Deal 9 damage. Weak 2.',
    baseDamage: 6,
    upgradedDamage: 9,
    starterRole: 'sage',
    vfxSequenceId: 'Seq_IceShard',
    vfxTarget: 'self_to_target',
  },
  {
    id: 's-frost-shield',
    name: 'Frost Shield',
    cost: 0,
    trait: 'frost',
    description: 'Gain 4 Block.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Frost Shield+',
    upgradeDescription: 'Gain 6 Block.',
    baseBlock: 4,
    upgradedBlock: 6,
    starterRole: 'sage',
  },
  {
    id: 's-blizzard',
    name: 'Blizzard',
    cost: 2,
    trait: 'frost',
    description: 'Deal 6 damage to all. Weak 1.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Blizzard+',
    upgradeDescription: 'Deal 9 damage to all. Weak 2.',
    baseDamage: 6,
    upgradedDamage: 9,
    isAoe: true,
    starterRole: 'sage',
  },
  // ── Storm (3 starters) ─────────────────────────────────────────
  {
    id: 's-zap',
    name: 'Zap',
    cost: 0,
    trait: 'storm',
    description: 'Deal 3 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Zap+',
    upgradeDescription: 'Deal 5 damage.',
    baseDamage: 3,
    upgradedDamage: 5,
    starterRole: 'sage',
  },
  {
    id: 's-arc-bolt',
    name: 'Arc Bolt',
    cost: 1,
    trait: 'storm',
    description: 'Deal 8 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Arc Bolt+',
    upgradeDescription: 'Deal 11 damage.',
    baseDamage: 8,
    upgradedDamage: 11,
    starterRole: 'sage',
  },
  {
    id: 's-thunderstrike',
    name: 'Thunderstrike',
    cost: 2,
    trait: 'storm',
    description: 'Deal 14 damage.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Thunderstrike+',
    upgradeDescription: 'Deal 19 damage.',
    baseDamage: 14,
    upgradedDamage: 19,
    starterRole: 'sage',
  },
  // ── Arcane (3 starters) ────────────────────────────────────────
  {
    id: 's-arcane-bolt',
    name: 'Arcane Bolt',
    cost: 1,
    trait: 'arcane',
    description: 'Deal 6 damage.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Arcane Bolt+',
    upgradeDescription: 'Deal 9 damage.',
    baseDamage: 6,
    upgradedDamage: 9,
    starterRole: 'sage',
  },
  {
    id: 's-mystic-shield',
    name: 'Mystic Shield',
    cost: 0,
    trait: 'arcane',
    description: 'Gain 3 Block. Heal 1.',
    upgraded: false,
    upgradeThreshold: 3,
    upgradeName: 'Mystic Shield+',
    upgradeDescription: 'Gain 5 Block. Heal 2.',
    baseBlock: 3,
    upgradedBlock: 5,
    baseHeal: 1,
    upgradedHeal: 2,
    starterRole: 'sage',
  },
  {
    id: 's-arcane-blast',
    name: 'Arcane Blast',
    cost: 2,
    trait: 'arcane',
    description: 'Deal 12 damage.',
    upgraded: false,
    upgradeThreshold: 2,
    upgradeName: 'Arcane Blast+',
    upgradeDescription: 'Deal 16 damage.',
    baseDamage: 12,
    upgradedDamage: 16,
    starterRole: 'sage',
  },
];

export { SAGE_STARTER };
